# Generated by Django 5.2.1 on 2025-05-14 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_id', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad')], max_length=2)),
                ('numero_id', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('contraseña', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'Petición'), ('Q', 'Queja'), ('R', 'Reclamo'), ('S', 'Sugerencia')], max_length=1)),
                ('comentarios', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='pqrs/')),
                ('fecha_radicado', models.DateTimeField(auto_now_add=True)),
                ('numero_radicado', models.CharField(max_length=15, unique=True)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('PROCESO', 'En proceso'), ('RESUELTO', 'Resuelto'), ('RECHAZADO', 'Rechazado')], default='NUEVO', max_length=10)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqrs.cliente')),
            ],
        ),
    ]
