# Generated by Django 5.2.1 on 2025-05-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='correo_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
