# Generated by Django 5.2.1 on 2025-05-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0003_gestor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gestor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
